export type ADD_LIST = "ADD_LIST";
export type REMOVE_LIST = "REMOVE_LIST";
export type EDIT_NAME_LIST = "EDIT_NAME_LIST";
export type CHANGE_POSITION_TASKS = "CHANGE_POSITION_TASKS";

interface IListConstants {
  ADD_LIST: ADD_LIST;
  REMOVE_LIST: REMOVE_LIST;
  EDIT_NAME_LIST: EDIT_NAME_LIST;
  CHANGE_POSITION_TASKS: CHANGE_POSITION_TASKS;
}

export const listConstants: IListConstants = {
  ADD_LIST: "ADD_LIST",
  REMOVE_LIST: "REMOVE_LIST",
  EDIT_NAME_LIST: "EDIT_NAME_LIST",
  CHANGE_POSITION_TASKS: "CHANGE_POSITION_TASKS"
};
