export type ADD_TASK = "ADD_TASK";
export type REMOVE_TASK = "REMOVE_TASK";
export type EDIT_TASK_NAME = "EDIT_TASK_NAME";
export type EDIT_TASK_DESCRIPTION = "EDIT_TASK_DESCRIPTION";

interface ITaskConstants {
  ADD_TASK: ADD_TASK;
  REMOVE_TASK: REMOVE_TASK;
  EDIT_TASK_NAME: EDIT_TASK_NAME;
  EDIT_TASK_DESCRIPTION: EDIT_TASK_DESCRIPTION;
}

export const taskConstants: ITaskConstants = {
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  EDIT_TASK_NAME: "EDIT_TASK_NAME",
  EDIT_TASK_DESCRIPTION: "EDIT_TASK_DESCRIPTION"
};
