export type ADD_TASK = "ADD_TASK";
export type MOVE_TASK = "MOVE_TASK";
export type EDIT_TASK_NAME = "EDIT_TASK_NAME";
export type EDIT_TASK_DESCRIPTION = "EDIT_TASK_DESCRIPTION";
export type CHANGE_POSITION_TASK = "CHANGE_POSITION_TASK";

interface ITaskConstants {
  ADD_TASK: ADD_TASK;
  MOVE_TASK: MOVE_TASK;
  EDIT_TASK_NAME: EDIT_TASK_NAME;
  EDIT_TASK_DESCRIPTION: EDIT_TASK_DESCRIPTION;
  CHANGE_POSITION_TASK: CHANGE_POSITION_TASK;
}

export const taskConstants: ITaskConstants = {
  ADD_TASK: "ADD_TASK",
  MOVE_TASK: "MOVE_TASK",
  EDIT_TASK_NAME: "EDIT_TASK_NAME",
  EDIT_TASK_DESCRIPTION: "EDIT_TASK_DESCRIPTION",
  CHANGE_POSITION_TASK: "CHANGE_POSITION_TASK"
};
